config/routes.rb
Rails.application.routes.draw do
  resources :projects
  root "pages#home"
  get "about", to: "pages#about", as: :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_rich_text :body
  has_many_attached :images, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true


  scope :published, -> { where(published: true) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:home]
  def home
    @projects = Project.published.with_attached_images.with_rich_text_body.order(created_at: :desc).limit(10)
  end

  def about; end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: "Project was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: "Project was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: "Project was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :body, :published, images: [])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
  def label_classes
    'block text-gray-700 text-sm font-bold mb-2'
  end

  def input_classes
    'block border-4 border-black w-full p-2 mb-6'
  end

  def render_form_field(f, field_name)
    render partial: "application/forms/fields/#{field_name}", locals: { f: f }
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/application/_nav.html.haml
%nav
  %ul{class: 'navbar'}
    %li
      = link_to root_path do
        = inline_svg 'logo.svg', class: 'logo'
    %li
      = link_to 'About', '#'
    %li
      = link_to 'Contact', '#contact'
    %li 
      = link_to 'Download CV', '#', class: 'py-2 px-4 border-2 border-purple-custom rounded-md text-purple-custom hover:bg-purple-custom hover:text-white transition duration-300 ease-in-out'

app/views/application/forms/_errors.html.haml
- if object.errors.any?
  #error_explanation
    %h2= "#{pluralize(object.errors.count, "error")} prohibited this project from being saved:"
    %ul
      - object.errors.full_messages.each do |message|
        %li= message

app/views/application/forms/fields/_images_field.html.haml
.field
  =f.label :images, class: label_classes
  = f.file_field :images, direct_upload: true, multiple: true, class: input_classes

app/views/application/forms/fields/_published_field.html.haml
.field
  = f.label :published, class: 'text-sm font-medium text-gray-900'
  = f.check_box :published, class: 'w-4 h-4 text-green-600 bg-gray-100 border-gray-300 rounded focus:ring-green-500'

app/views/application/forms/fields/_rich_text_body_field.html.haml
.field
  = f.label :body, class: label_classes
  = f.rich_text_area :body, class: input_classes

app/views/application/forms/fields/_submit.html.haml
.actions.mb-5
  = f.submit 'Save', class: 'submit-btn text-emerald-100 bg-emerald-500 hover:bg-emerald-600 hover:text-emerald-700'

app/views/application/forms/fields/_title_field.html.haml
-# Takes a form object and renders a title field

.field
  = f.label :title, class: label_classes
  = f.text_field :title, class: input_classes

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DigitalCard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'nav' %>
    <main class=''>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_home_hero.html.haml
%section{class: 'grid grid-cols-1 hero-height lg:grid-cols-5'}
  %div{class: 'bg-white p-4 col-span-3'}
    .flex.flex-col.justify-center.items-center.w-full.h-full

      .max-w-2xl
        %h1.text-6xl.font-bold.mb-10
          Hey there, 
          %br
          I'm Martin Yanchev!
        %p{class: 'text-2xl mb-5'}  A dedicated full-stack developer based in the city of Glasgow, Scotland.

        %p{class: 'text-2xl mb-10'}  I thoroughly enjoy architecting sophisticated web applications and immersing myself in various technological platforms, including Ruby, Python, Java, and Javascript.
      .flex.gap-5
        = link_to 'Check out my CV', '#', class: ''

  %div{class: 'p-4 col-span-2'}
    .flex.flex-col.justify-center.items-center.w-ful.h-full
      = image_tag 'me.png'

app/views/pages/_home_projects.html.haml
%section
  %h1 Projects

app/views/pages/_project.html.haml
.flex.flex-col.gap-5.bg-white.relative.p-5.project-cards-border{class: 'shadow-[rgba(0,_0,_0,_0.24)_0px_3px_8px]'}
  %h2.text-xl.font-bold= project.title
  %p.text-gray-500= project.body.to_plain_text.truncate(100)
  .py-5
    = image_tag project.images.first, class: 'w-full h-48 object-cover'
  
  = link_to 'Learn more', project, class: 'bg-emerald-500 hover:bg-emerald-700 text-white font-bold py-2 px-4 rounded text-center'
  

app/views/pages/about.html.haml
= turbo_frame_tag 'modal' do
  = render TurboModalComponent.new(title: "About me") do
    = render "about_modal"

app/views/pages/home.html.haml
= render 'home_hero'
= render 'home_projects'

app/views/projects/_form.html.haml
= form_for @project, html: { class: 'flex flex-col space-y-5'} do |f|

  = render 'application/forms/errors', object: @project
  = render_form_field f, :title_field
  = render_form_field f, :images_field
  = render_form_field f, :rich_text_body_field
  = render_form_field f, :published_field

  = render_form_field f, :submit

app/views/projects/edit.html.haml
%div{class: 'mx-auto w-full max-w-2xl'}

  %h1 Editing project

  = render 'form'

  = link_to 'Show', @project
  \|
  = link_to 'Back', projects_path

app/views/projects/index.html.haml
%h1 Listing projects

%table
  %thead
    %tr
      %th Title
      %th Body
      %th Published
      %th
      %th
      %th

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.title
        %td= project.body
        %td= project.published
        %td= link_to 'Show', project
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Project', new_project_path

app/views/projects/new.html.haml
%div{class: 'mx-auto w-full max-w-2xl'}
  %h1 New project
  = render 'form'

  = link_to 'Back', projects_path

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @project.title
%p
  %b Body:
  = @project.body
%p
  %b Published:
  = @project.published

= link_to 'Edit', edit_project_path(@project)
\|
= link_to 'Back', projects_path